// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsa7yhQ7AeCVAzalb7vHy6hvuTUTMUENk',
    appId: '1:531545866205:web:23187d63905498137d4034',
    messagingSenderId: '531545866205',
    projectId: 'doctor-app-ce679',
    authDomain: 'doctor-app-ce679.firebaseapp.com',
    storageBucket: 'doctor-app-ce679.appspot.com',
    measurementId: 'G-DL64M28XXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPnT3cycUtjpRsVnTlDl-HTYxdaO7hUtc',
    appId: '1:531545866205:android:3d44b9d7bb513fb87d4034',
    messagingSenderId: '531545866205',
    projectId: 'doctor-app-ce679',
    storageBucket: 'doctor-app-ce679.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuKMWEGiFCuQ41txemAFsk4og_XT4Nq10',
    appId: '1:531545866205:ios:1f5951215e2e756f7d4034',
    messagingSenderId: '531545866205',
    projectId: 'doctor-app-ce679',
    storageBucket: 'doctor-app-ce679.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuKMWEGiFCuQ41txemAFsk4og_XT4Nq10',
    appId: '1:531545866205:ios:e54edfe78a1abf307d4034',
    messagingSenderId: '531545866205',
    projectId: 'doctor-app-ce679',
    storageBucket: 'doctor-app-ce679.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
